# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vitaliy Kozharskiy 

  Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081
     
  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian-lxc"
    vb.memory = "512"
  end
  
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
  config.vm.provision "shell", path: "lxc.sh"
end