# -*- mode: ruby -*-
# vi: set ft=ruby :
# Kozharskiy Vitaliy


Vagrant.configure("2") do |config|
  config.vm.box = "kozharskiy-vitaliy/centos8-lamp-template"
  ext_ip = "192.168.1.1"
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", guest_ip: ext_ip
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1", guest_ip: ext_ip

  config.vm.network "private_network", ip: ext_ip
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos8-lamp-sites"
    vb.memory = "512"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
   
    sudo chmod -v 775 /var/www/html
    sudo chown -vR root:vagrant /var/www/html
    sudo cp /vagrant/index.html /var/www/html

    sudo mkdir -pv /var/www/php/
    sudo chmod -v 775 /var/www/php
    sudo chown -vR root:vagrant /var/www/php
    sudo cp /vagrant/index.php /var/www/php/

    # Config VirtualHost  
    sudo mkdir -pv /etc/httpd/sites-available
    sudo chmod -v 775 /etc/httpd/sites-available
    sudo chown -vR root:vagrant /etc/httpd/sites-available	

    sudo mkdir -pv /etc/httpd/sites-enabled
    sudo chmod -v 775 /etc/httpd/sites-enabled
    sudo chown -vR root:vagrant /etc/httpd/sites-enabled
    
    # Disable files which use for example    

    sudo mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.bak
    sudo mv /etc/httpd/conf.d/userdir.conf /etc/httpd/conf.d/userdir.conf.bak
    sudo mv /etc/httpd/conf.d/autoindex.conf /etc/httpd/conf.d/autoindex.conf.bak

    # Copy files which use for project

    sudo cp /vagrant/site80.conf /etc/httpd/conf.d/site80.conf
    sudo cp /vagrant/site81.conf /etc/httpd/conf.d/site81.conf

    # Change files for virtual hosts

    sudo cp /vagrant/site80.conf /etc/httpd/sites-available/site80.conf
    sudo cp /vagrant/site81.conf /etc/httpd/sites-available/site81.conf

    sudo ln -svf /etc/httpd/sites-available/site80.conf /etc/httpd/sites-enabled/site80.conf
    sudo ln -svf /etc/httpd/sites-available/site81.conf /etc/httpd/sites-enabled/site81.conf
    
    # Add listen ports 80 and 81

    sed -i.bak -e "/Listen 80/a Listen 81" /etc/httpd/conf/httpd.conf

    # Apache service Restarting
    sudo systemctl restart httpd
  SHELL
end
