version: '3'
services:
  jenkins:
    build:
      context: ./files-jenkins
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - /vagrant/:/vagrant/
      - ./files-jenkins/jobs/:/var/lib/jenkins/jobs/
      - ./files-jenkins/master.key:/var/lib/jenkins/secrets/master.key
      - ./files-jenkins/hudson.util.Secret:/var/lib/jenkins/secrets/hudson.util.Secret
      - ./files-jenkins/credentials.xml:/var/lib/jenkins/credentials.xml
      - /var/run/docker.sock:/var/run/docker.sock   
      - temp:/var/lib/jenkins/workspace 
    networks:
      - network_kozhvit
    container_name: jenkins-kozharskiy    
  nexus:
    build:
      context: ./files-nexus
      dockerfile: Dockerfile
    ports:
      - "81:8081"  
    volumes:
      - /vagrant/:/vagrant/
    networks:
      - network_kozhvit
    container_name: nexus-kozharskiy  
networks: 
  network_kozhvit:      
volumes: 
  temp: