Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/bionic64"
	config.vm.hostname = "docker.vm"
	
	# vagrant plugin install vagrant-disksize
	config.disksize.size = '20GB'
	
	config.vm.network "forwarded_port", guest: 80, host: 80
	config.vm.network "forwarded_port", guest: 81, host: 81

	config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus   = "2"
      vb.name   = "docker.vm"
    end

  config.vm.provision "shell", path: "docker-install.sh"
end


