# Dockerfile.multi from Kozahrskiy Vitaliy
FROM golang:latest as build
SHELL ["/bin/bash", "-c"]
RUN git clone https://github.com/L-Eugene/word-cloud-generator.git \
&& cd /go/word-cloud-generator && make

FROM alpine:latest as production
COPY --from=build /go/word-cloud-generator/artifacts/linux/word-cloud-generator /
RUN chmod +x /word-cloud-generator
ENTRYPOINT nohup /word-cloud-generator

