Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.hostname = "docker.vm"
	
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.network "forwarded_port", guest: 8081, host: 8081

	config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus   = "2"
      vb.name   = "docker.vm"
    end

  config.vm.provision "shell", path: "docker-install.sh"
end